ver: "1.0"
rules:
  silero_1:
    senders: []
    before_ext: []
    purposes: [say_silero]
    acceptors: [silero]
#intent_examples:
#  stop_gen_voice_silero: ["замолчи", "стоп", "отмена", "прекрати", "остановись"]