ver: "1.0"
rules:
  tg_userbot_1:
    senders: []
    before_ext: [save_value, add_qdrant_context, [ask_gpt, {prompt: 'Ты общаешься в чате, у тебя спросили: "%event_value%"
Для ответа ты можешь использовать контекст:
%event_qdrant_context%

***
Если с учетом всех данных невозможно ответить на вопрос - Напиши что ответишь как только будет возможность'}], [change_purpose, {new_purpose: "outcoming_tg_userbot"}]]
    purposes: [incoming_tg_bot]
    acceptors: [tg_userbot]
  tg_userbot_2:
    senders: []
    before_ext: [[ask_gpt, {prompt: 'Сформируй json для сообщения: "%event_old_value%"
Список известных пользователей - список из id и имен пользователя:
%event_allowed_chats%
***

Пример: "напиши максиму как дела"
Ответ:
{
  "chat_id": 23874295,
  "type": "text",
  "text": "Как дела?"
}

***
Если нет подходящего пользователя - пришли пустой json: {}
В ответ не пиши ничего кроме json'}], [change_purpose, {new_purpose: "send_message"}]]
    purposes: [outcoming_tg_userbot]
    acceptors: [tg_userbot]

intent_examples:
 enable_tg_userbot: [
   "включи телеграм автоответчик",
   "включи автоответчик в телеграм",
   "включи юзеербота",
   "активируй юзербота",
   "запусти юзербота"
 ]
 disable_tg_userbot: [
   "выключи телеграм автоответчик",
   "выключи автоответчик в телеграм",
   "выключи юзеербота",
   "отключи юзербота",
   "отключи автоответчик в телеграм",
   "останови юзербота"
 ]